### ISSUE TITLE
Home page fails to open on Firefox (MacOS)

### ISSUE THREAD

**Issue by lellingsen** [t-eckert/devy#27]
Seeing this error in my console:

<img width="541" alt="Screenshot 2024-08-19 at 9 14 17 AM" src="https://github.com/user-attachments/assets/8ca00119-9eb0-4f5c-8ed1-03374073c049">

**Comment by t-eckert** [comment]
Oh interesting! Thank you for catching this. Set.difference() is supported in Firefox 126 and above, but I'll find a way to not use it.

**Comment by t-eckert** [comment]
https://github.com/t-eckert/devy/commit/fb65dc96ebab7ac62c1847aa67fb8e5dfd163f81

That patch should fix it. Let me know if you still see this.
